### PR TITLE
Apply OMP style to documentation

### PR DESCRIPTION
**Pull request by LuLeRoemer**
This PR integrates a modified Antora default UI that contains design changes complying with the OMP corporate design. The PR closes issue #19.

### CODE REVIEW

**Review by atextor — APPROVED** [review]
Although I'll approve, I must ask: Wouldn't it make more sense to first release a first version of sds-antora-ui (with OFL license and disclaimer added there), then remove the temporary Antora ui-bundle.zip from this repository and use a hyperlink to the released UI instead in site.yml? This way there would not have to be references to licenses and related things that don't have anything to do with the actual content of this repository.

**Review by BirgitBoss — APPROVED** [review]
approved (although I did not look into the ui-bundle.zip but I saw the result)

**Comment by eriksven** [comment]
In general, I agree that the approach outlined by @atextor makes more sense in the long run and we should therefore aim for this once we were able to perform all the necessary and described steps. 
In the meantime, the intention of this specific PR is to provide a quick fix to the issue that the current style for the documentation did not include the OMP style yet.

**Review by eriksven — APPROVED** [review]
To my understanding, this PR does not make any functional or otherwise technical changes to BAMM and fixes the issue that we did not apply an OMP specific style to the documentation yet.

**Pull request merged**
